### PR TITLE
Rocker hot reload documentation

### PR DESCRIPTION
**Pull request by jiachen1120**
Added missing document

Related issue: https://github.com/networknt/light-codegen/issues/225

### CODE REVIEW

**Comment by stevehu** [comment]
@jiachen1120 There is also a ps1 script for Window in the codegen-cli folder. Could you please add a section on how to use the script for Windows users? Thanks.

**Comment by jiachen1120** [comment]
@stevehu The windows part updated. There seems no big different between them.

**Comment by dz-1** [comment]
The ps1 script should be run in 'Powershell ISE', not 'IES'. Our windows settings blocks Powershell scripts.
If the codegen scripts are used, users do not need to create 'rocker-compiler.conf' themselves. 

Users only need to make sure:
1. the working dir has `codegen-cli.jar` from the `codegen-cli/target` folder;
2. the templates in the working dir have the same folder structures as provided templates.

**Comment by jiachen1120** [comment]
@dz-1 Thanks!

**Pull request merged**
