### PR TITLE
Update client.md

### PR DESCRIPTION
**Pull request by jiachen1120**
Specified how to configure the keystore and truststore path in client.yml when using externalized path

### CODE REVIEW

**Comment by stevehu** [comment]
@jiachen1120 should we use trustStore: `client.truststore` instead of `trustStore: ssl/client.truststore` as most of our users are flattened all config files into one folder these days especially for Kubernetes secret creation.

**Comment by NicholasAzar** [comment]
@jiachen1120 could you also maybe add a note in this file: 
- https://github.com/networknt/light-doc/blob/master/content/en/tutorial/client/configuration.md

**Comment by jiachen1120** [comment]
@stevehu Hey! the modification is to amplify the path of keystore and truststore should be relative to the externalized config path. Our framework support both flatten config and relative path. So, I think we should add these details for guidance. I added the flatten scenario case after the modification.

**Comment by stevehu** [comment]
@jiachen1120 Sorry. I misunderstood the purpose. Now with both options documented, it is much better. Thanks.

**Pull request merged**
